### ISSUE TITLE
Les-simple数据集中很多passage没有question，有question的不到1/3?

### ISSUE THREAD

**Issue by chaoyushi** [caishiqing/joint-mrc#11]

**Comment by caishiqing** [comment]
你好，第二届莱斯杯的数据是这样的，一个问题有5个候选篇章，只有一个篇章包含答案，所以理论上有question的篇章只有1/5，但有些篇章对不同问题是复用的，所以这个比例再提高点，大概就是你统计的这个量，所以是没有问题的。
这个数据集本身就是篇章很多很长，负样本很多。

**Comment by chaoyushi** [comment]
> 你好，第二届莱斯杯的数据是这样的，一个问题有5个候选篇章，只有一个篇章包含答案，所以理论上有question的篇章只有1/5，但有些篇章对不同问题是复用的，所以这个比例再提高点，大概就是你统计的这个量，所以是没有问题的。
> 这个数据集本身就是篇章很多很长，负样本很多。

okk
